### ISSUE TITLE
[Epic] Install the Carbon Aware SDK as a Package

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#152]
### Goal

Design and convert the Carbon Aware SDK to be used as a package within code. The goal of the customer is to simplify the hosting of the SDK as the customer does not allow HTTP connections to be opened.

### Success Metrics

- The Carbon Aware SDK can run in a closed network with access to Electricity Map being the only external traffic allowed.
- The Carbon Aware SDK is not called from an HTTP connection.
- A script is provided on how to create and publish the package.

#### Design and Specification 📔

- [x] Design Document  #153 
- [x] Architectural Decision Record(s) 

- [SDK Packaging](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0010-sdk-packaging.md)
- [SDK as a C# library](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0009-sdk-as-a-c%23-client-library.md)

#### Engineering ⚙️

- [x] #160 
- [x] #165 
- [x] #166 

#### Release Planning

- [ ] Integration tests are complete
- [ ] Demo the feature internally
- [ ] Pull Request created in GSF/dev branch

**Comment by gfmatthews** [comment]
Notes: We are not publishing the package ourselves nor are we forcing anyone to publish the package for us. In scope is only providing the script that would allow some entity to run the "pipeline" or "script" and then ingest the package in whatever way they see fit.
