### ISSUE TITLE
[Design] Convert Carbon Aware SDK into a Library

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#153]
# Description

As a Carbon Aware Developer, I need to use the Carbon Aware SDK as a library so that I can access the SDK without opening and HTTP connection.

# Acceptance Criteria

- [x] Design needs to consider how to support the same .NET versions as [Azure Functions 4.0](https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#supported-versions)
- [x] Design needs to consider how to expose the SDK API routes as a library and while keeping the Aggregator functionality hidden to the user.
- [x] Design needs to satisfy supporting multiple languages for error messages within the package 
- [x] Design needs to consider how to work with Config Files within the code as well as ensuring the config files are installed and uninstalled with the package
- [x] Designed needs to consider allowing consumers to step into the code while debugging
- [x] Design needs to consider package versioning
- [x] Final architectural decisions proposed in an [Architectural Decision Record log](https://github.com/microsoft/carbon-aware-sdk/tree/dev/docs/architecture/decisions)

# Out of Scope

We will be providing guidance on how to publish the SDK as a package, but we will not be publishing the package. 

# Dependencies

The customer is considering using the library as part of an Azure Function, so there is a dependency to meet the requirements of Azure Functions.

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Engineering team understands acceptance criteria
- [x] External / 3rd Party dependencies identified

# Tasks
- [x] Add Library section
   - [x] Goals
   - [x] Non Goals
   - [x] Proposed design
     - [x] Short term
     - [x] Long term
- [x] Add Packaging section
  - [x] Goals
  - [x] Non Goals
  - [x] Proposed Design
 - [x] Write ADR
   - [x] SDK as a C# client library ADR [PR 153](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/153)

**Comment by juzuluag** [comment]
Hi @esgraham and @gfmatthews . Design doc has been updated with the estimates (see page 2 - **Effort** comments)
CC'ing @JenMadiedo
