### ISSUE TITLE
[Epic] Add Electricity Maps as a Data Source to the Carbon Aware SDK

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#154]
### Goal

[Electricity Maps](https://www.electricitymaps.com/) is a third-party API that provides Marginal Carbon Intensity Rates as well as breakdown information on where the Carbon is being generated (nuclear, solar, etc).  Electricity Map has consistently been proven to provide more accurate Carbon Intensity rates in Europe.  

For the Carbon Aware SDK project involving Electricity Maps, there are two goals

- Provide another data source to the Carbon Aware SDK so that it can be more widely adopted.
- Prove that the architecture designed by the CSE team works and can be reused.

### Success Metrics

- Provide the Average Carbon Intensity over the Azure Batch duration using Electricity Maps Data
- Provide the lowest Forecasted Average Carbon Intensity Rate over the Azure Batch duration using Electricity Maps Data

While not required by the current customer for the MVP, we do expect to implement the batch functionality so that future customers can provide reports on both the Actual and Forecasted data.

#### Design and Specification 📔

- [x] Design Document #155
- [x] Architectural Decision Record(s)

- [Data Source Registration](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0006-data-source-registration.md)
- [Data Source Interfaces](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0007-data-source-interfaces.md)
- [Data Source Configuration](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0008-data-source-configuration.md)

#### Engineering ⚙️

- [x] #161 
- [x] #164 
- [x] #163 
- [x] #167 

#### Release Planning

- [ ] Integration tests are complete
- [ ] Demo the feature internally
- [ ] Pull Request created in GSF/dev branch
