### ISSUE TITLE
[Design] : Add Electricity Maps as a Data Source to the Carbon Aware SDK

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#155]
# Description

As Carbon Aware SDK user, I would like use the Electricity Maps API as a data source, so that I can get the average marginal carbon intensity rates and the lowest forecasted carbon intensity rate from Electricity Maps.

# Acceptance Criteria

- [x] Design provides specifications on how to add Electricity Maps as a data source to the SDK with the same or as close to functionality as the WattTime data source
- [x] Design identifies any changes that are needed due to Electricity Map differences.
- [x] Final architectural decisions proposed in an [Architectural Decision Record log](https://github.com/microsoft/carbon-aware-sdk/tree/dev/docs/architecture/decisions)

# Dependencies

The implementation is dependent on [Electricity Map API](https://static.electricitymaps.com/api/docs/index.html#introduction) functionality.  

# Sprint-Ready Checklist

- [x] Acceptance criteria defined 
- [x] Engineering team understands acceptance criteria
- [x] External / 3rd Party dependencies identified

# Tasks

- [x] Create shared word document to draft early designs
- [x] **Design Area: ElectricityMapsDataSource project** @pritipath 
- [x] Design Area: ICarbonIntensityDataSource interface @bderusha 
- [x] Design Area: Config @pritipath 
- [x] Design Area: Integration Testing @bderusha @pritipath 
- [x] Design Area: Telemetry & Logging
- [x] Design Area: ErrorHandling

- [x] Update design doc with: @pritipath 
    - [x] Estimates for the proposals that we want to move forward
    - [x] Proposals organized by priority & dependency
- [x] Combine with library proposals. @bderusha 
- [x] Determine global priority @bderusha 
- [x] Create ADRs from joint documents.
    - [x] Config ADR [PR 148](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/148)
    - [x] Interface ADR [PR 147](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/147)
    - [x] DataSource Registration ADR [PR 146](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/146)

## Design Area: ElectricityMapsDataSource project

- Handle auth (Ask A-team for credentials when ready)
- Understand if EM can support all existing interface methods, and what "work" it will take to do so.
- Understand what additional EM functionality we cannot expose with the current interface.
- Would like to have a "separate" EMclient that lives within the EMDataSource project (rather than outside of it like WattTimeClient)

## How Should We Estimate Work

Estimates include anything which would be required by our team to merge the feature.
Estimate Unit: sprints (2 people for 2 weeks)

**Comment by bderusha** [comment]
@esgraham This is complete.  We can close whenever you would like.
