### ISSUE TITLE
Create a C# API Contract that exists as a consumer layer for Forecast and Marginal Routes

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#160]
# Description
As a developer of a carbon-aware application, I want to consume the Forecast and Average Carbon Intensity api as c# library so that I can run the SDK within a single application.

[SDK as a Library ADR](https://github.com/microsoft/carbon-aware-sdk/blob/153/sdkToLibraryADR/docs/architecture/decisions/0009-sdk-as-a-c%23-client-library.md)

# Acceptance Criteria

- [x] Ensure the developer can access the emissions/forecasts/current API
- [x] Ensure that the current forecast result is returned to the application when the emissions/forecasts/current API is called
- [x] Ensure that developer can access the emissions/average-carbon-intensity API
- [x] Ensure that the average carbon intensity result is returned to the application when the emissions/average-carbon-intensity API is called
- [x] Unit Tests are completed and code passes tests
- [x] Documentation is provided for Forecast API
- [x] Documentation is provided for Average Carbon Intensity API

# Dependencies

The C# API Contract Layer is dependent on the existing CarbonAware.Aggregator.
The acceptance criteria is dependent on one Data Source being available to return a result.  This does not need to be Electricity Maps.

https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/171

# Task List
- [x] Define namespace for library
- [x] Define data types that are returned to user
- [x] Implement IEmissionHandler + EmissionHandler for `average`
- [x] Implement IForecastHandler + ForecastHandler for `current`
- [x] Add docs + unit tests for forecast handler
- [x] Add docs + unit tests for emissions handler
- [x] Add a basic class for wrapping exceptions

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [x] External / 3rd Party dependencies identified
- [x] Engineering team understands acceptance criteria 
- [x] Is the user story small enough to be implemented in a short amount of time (2 weeks), but large enough to provide value?

**Comment by esgraham** [comment]
PR:  https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/185

**Comment by esgraham** [comment]
Merged into GSF repo
