### ISSUE TITLE
Decouple the IEmissionsDataSource and IForecastDataSource Interface

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#161]
# Description
As a Carbon Aware Data Source developer, I want to add new data sources that may not have all current SDK functionality - including data sources that have only Emissions data but not Forecast data, so I can plug the data source into the SDK without having to throw a NotImplementedException for functionality that does not exist in the data source.

[Data Source Interfaces ADR](https://github.com/microsoft/carbon-aware-sdk/blob/155/interface-segregation-adr/docs/architecture/decisions/0007-data-source-interfaces.md)

# Acceptance Criteria

- [x] Ensure that the IEmissionsDataSource  interface can be implemented by a data source developer without implementing the IForecastDataSource interface
- [x] Ensure that the IForecastDataSource interface can be implemented by a data source developer without implementing the IEmissionsDataSource interface
- [x] Unit Tests are completed and code passes tests

**Verify that the following WebAPI routes can be executed and return the expected results:**
- [x] [GET emissions/bylocation](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#get-emissionsbylocation)
- [x] [GET emissions/bylocations](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#get-emissionsbylocations)
- [x] [GET emissions/bylocations/best](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#get-emissionsbylocationsbest)
- [x] [GET emissions/forecasts/current](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#get-emissionsforecastscurrent)
- [x] [POST emissions/forecasts/batch](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#post-emissionsforecastsbatch)
- [x] [GET emissions/average-carbon-intensity](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#get-emissionsaverage-carbon-intensity)
- [x] [POST emissions/average-carbon-intensity/batch](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#post-emissionsaverage-carbon-intensitybatch)

**Verify that the that following CLI routes can be executed and return the expected results:**
- [x] [emissions](https://github.com/microsoft/carbon-aware-sdk/blob/dev/docs/carbon-aware-cli.md#emissions)
- [x] [emissions-forecasts](https://github.com/microsoft/carbon-aware-sdk/blob/dev/docs/carbon-aware-cli.md#command-emissions-forecasts)

# Dependencies

https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/170

# Task List
- [x] Create IEmissionsDataSource, NullEmissionsDataSource, EmissionsAggregator + Tests, Updates Consumers @bderusha 
- [x] Create IForecastDataSource, NullForecastDataSource, ForecastAggregator + Tests, Updates Consumers @pritipath 
- [x] JSON data source config changes
- [x] WattTime data source config changes
- [x] Update default config to use NullDataSources
- [x] clean up step of removing unused refactored code.
POSSIBLE PR AT THIS POINT
- [x] Split config into two data source
- [x] require that AT LEAST ONE data source is configured
- [x] remove forecasting methods and interface from JSON
- [x] Update documentation for configuring data sources
CREATE FINAL PR

Working agreement to delete at little as possible, and just c+p to new classes
Need to document for each other if and when we change any ported code.

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [x] External / 3rd Party dependencies identified
- [x] Engineering team understands acceptance criteria 
- [x] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by esgraham** [comment]
PR: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/187

**Comment by esgraham** [comment]
Merged
