### ISSUE TITLE
Align `dev` branch with GSF

### ISSUE THREAD

**Issue by bderusha** [microsoft/carbon-aware-sdk#162]
# Description

Microsoft fork has features on `dev` which have not been contributed back to the GSF, this causes drift and makes it hard to contribute features in the future.  We must contribute back everything in shared files on our `dev` branch to ensure future development is in-line with the parent project. Files unique to the fork can live in a specific commit (`6696b8cb`)

# Acceptance Criteria

- [x] Microsoft fork can stay current with the GSF `main` & `dev` branches without losing functionality

# Dependencies

# Task List

**Prepare PRs for:**

- [x] ADR-0005
- [x] CLI
- [x] JSON data source bug fix
- [x] LocationSource
- [x] Github Templates

**PRs merged for:**

- [x] ADR-0005 (this is not blocking)
- [x] CLI
- [x] JSON data source bug fix
- [x] LocationSource
- [x] Github Templates

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [x] External / 3rd Party dependencies identified
- [x] Engineering team understands acceptance criteria 
- [x] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

# Pending Features

## ADR-0005

**Issue**: [Issue #126 · Green-Software-Foundation](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/126)
**PR**: [Pull Request #127 · Green-Software-Foundation](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/127)
**MS fork branch**: [623/ADR-0005-web-api-stream](https://github.com/microsoft/carbon-aware-sdk/tree/623/ADR-0005-web-api-stream)
**Dependencies**: None
**Status**: MERGED! 🎉 

## CLI

**Issue**: [Issue #131 · Green-Software-Foundation](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/131)
**PR**: [PR #158](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/158)
**MS fork branch**: `162/cli-redesign`
**Dependencies**: CarbonAwareParameters + Mock Refactor (both are now merged)
**Status**: MERGED! 🎉 

Previous branches for reference: [623/cli-redesign-with-dependencies](https://github.com/microsoft/carbon-aware-sdk/tree/623/cli-redesign-with-dependencies) + [623/cli-redesign](https://github.com/microsoft/carbon-aware-sdk/tree/623/cli-redesign) 

## JSON data source bug fix

**Issue**: [Issue #155](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/155)
**PR**: [PR #156](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/156)
**MS fork branch**: 162/json-bug-fix
**Dependencies**: 
**Status**: MERGED! 🎉 

## LocationSource

**Issue**: [Issue #95](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/95)
**PR**: [PR #157](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/157)
**MS fork branch**: `162/location-source`
**Dependencies**: 
**Status**: MERGED! 🎉 

## Github Templates

**Issue**: N/A
**PR**: N/A
**MS fork branch**: 162/github-templates-ms
**Dependencies**: None
**Status**:  Templates merged with larger ms-specific-files commit, ready to go in as first commit when `gsf/dev == ms/dev`

**Comment by gfmatthews** [comment]
This makes sense to do earlier than later as the longer we wait the harder and more work this will be. We also owe it to the GSF to contribute back all the features and stuff we worked on post v1.0. So, let's prioritize this early so we can close it out and keep ourselves out of tech debt holes.

**Comment by esgraham** [comment]
Complete
