### ISSUE TITLE
Update Data Source Configuration to allow Applications to use Multiple Data Sources

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#163]
# Description
As a Carbon Aware Application User, I want to use different data sources for different interfaces of the Carbon Aware SDK, so that I can use all the functionality of the SDK even if my chosen data source does not implement the full SDK functionality.

[Data Source Configuration ADR](https://github.com/microsoft/carbon-aware-sdk/blob/155/datsource-configuration-adr/docs/architecture/decisions/0008-data-source-configuration.md)

# Acceptance Criteria

- [ ] Ensure that the changes to the configuration allow an API call to WattTime and the expected result is returned without errors.
- [ ] Verify that the changes to the configuration allow the JSON data source to be used, and the expected result is returned without errors.
- [ ] Ensure that a carbon aware application can use one data source for Emissions and one data source for Forecast (example: JSON for emissions data, and WattTime for forecast data)
- [ ] Unit Tests are completed and code passes tests
- [ ] Documentation is provided that details the configuration scheme and provides an example

# Dependencies

The Data Source Configuration is dependent on [Decoupling the Interfaces](#161) 

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by bderusha** [comment]
@esgraham This story was implemented as part of #161

Would you prefer to close this story or move it to "blocked" as well until the dependent CLI work is merged?

**Comment by esgraham** [comment]
I will close the story.
