### ISSUE TITLE
Update Data Source Configuration to account for Unique Parameters

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#164]
# Description
As a Carbon Aware Data Source Developer, I want to allow for configuration of parameters that are specific to my data source, so that the data from the data source can be returned as the carbon aware user would like.

[Data Source Configuration ADR](https://github.com/microsoft/carbon-aware-sdk/blob/155/datasource-configuration-adr/docs/architecture/decisions/0008-data-source-configuration.md)

# Acceptance Criteria

- [x] Ensure that the data source configuration matches the schema proposed in [Data Source Configuration ADR](https://github.com/microsoft/carbon-aware-sdk/blob/155/datasource-configuration-adr/docs/architecture/decisions/0008-data-source-configuration.md)
- [x] Ensure that the changes to the configuration allow the WattTime data source to be configured and the expected result is returned without errors.
- [x] Ensure that the changes to the configuration allow the JSON data source to be configured and the expected result is returned without errors.
- [x] Verify that all data source-specific configuration values are contained in the "Configurations" object.
- [x] Verify that each data source configuration can have its own unique configurable values.
- [x] Verify that every data source configuration declares a "Type".
- [x] Verify that an interface which references a key in the "Configurations" object is used for that interface.
- [x] Verify that an interface which references a key which does not exist in the "Configurations" object throws an error with a clear, actionable message as early as possible.
- [ ] Unit Tests are completed and code passes tests
- [x] Documentation is provided that details the configuration scheme and provides an example
- [x] Data Source configuration documentation exists in `/docs/configuration.md`
- [x] Data Source configuration references in `/GettingStarted.md` _link_ to the relevant `/docs/configuration.md` section and do not duplicate content from that "source of truth"

# Dependencies

The Data Source Configuration is dependent on [Decoupling the Interfaces](#161) 
https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/172

# Open Questions
- Should configuration "Type" be the full namespace of the data source?
  - For right now, no.  Using the "short name" is fine.
- Should we support same-data source/different config scenarios?

# Task List
- [x] CarbonAwareVars config class -> DataSources config class
- [x] Implement the variables for interfaces, configurations, and mapping them together ^
- [x] Json data source config should be fully contained in a single config class
- [x] WattTime data source config should also be fully contained (will need move Client config around) ^
- [x] ServiceCollectionsExtensions updated to register configurations by interface value -> configurations key object && "Type"
- [x] ServiceCollectionsExtensions updated to register data sources as defined in the config
- [x] Documentation updates

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [x] External / 3rd Party dependencies identified
- [x] Engineering team understands acceptance criteria 
- [x] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by esgraham** [comment]
PR:  https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/190

**Comment by esgraham** [comment]
Merged
