### ISSUE TITLE
Create a Parameter Builder class

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#165]
# Description
As a Carbon Aware SDK Developer, I want to use parameters that are specific to the interface I am adding to the SDK, so that I do not need to understand how the SDK aggregators are called.

[SDK as a Library ADR](https://github.com/microsoft/carbon-aware-sdk/blob/153/sdkToLibraryADR/docs/architecture/decisions/0009-sdk-as-a-c%23-client-library.md)

# Acceptance Criteria

- [ ] Verify that the consumer cannot access and use the parameter builder
- [ ] Ensure that when parameters are used in an API call, the expected results are returned.
- [ ] Unit Tests are completed and code passes tests
- [ ] Documentation is provided for the SDK developers

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by bderusha** [comment]
This feature was created when the design proposed having end-users create the parameter objects as part of an overall push for a user-friendly SDK experience. The design has since, shifted such that users no longer need to interact with the parameter class at all. This substantially reduces the value of this work, as it only minorly improves the experience for core contributions extending existing aggregators. For that audience there are higher impact ways to improve the experience by removing code, rather than adding more.

As this feature is simply an artifact of a previous design proposal and would not have been generated out of the current design, I move that we delete this feature.

CC @esgraham @gfmatthews

**Comment by gfmatthews** [comment]
Closing per comment above.
