### ISSUE TITLE
Tooling and documentation to create the ingestible library package

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#166]
# Description
As a Carbon Aware Application Developer, I want to install the SDK as a C# Library from a package, so that I can use the SDK within my application.

[Library Packaging Design](https://microsoft.sharepoint-df.com/:w:/r/teams/CSEFSI/_layouts/15/WopiFrame2.aspx?action=edit&sourcedoc=%7B6b13b1ba-33a7-4999-aa84-c18d87645da0%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.bim&wdExp=TEAMS-TREATMENT&wdhostclicktime=1665679405968&web=1&cid=5e161777-f30e-4ecb-92aa-5a04b3911aa5)

# Acceptance Criteria

### Tooling

- [x] Ensure there is a tool identified and available to use for packaging. 
- [ ] Verify the package can be signed with a certificate.
- [x] Verify debug symbols are adding to the package.
- [x] Ensure a script is available that will build the package from a repository.

### Documentation: 

- [x] Document steps on how to generate CarbonAware packages. 
- [x] Document a Getting Started Guide on How to Write a Client/Consumer of the SDK

- [x] Verify the packaging will install within a C# application or Azure Function

# Dependencies

https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/182

# Task List
- [x] Create Github Action workflow
- [x] Test bash scripts on Linux/Unix
- [x] Test bash scripts on Windows
- [x] Add docs on how to create packages and consume
- [x] Modify .csproj files to include/exclude certain projects
- [x] Create demo gif

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [x] External / 3rd Party dependencies identified
- [x] Engineering team understands acceptance criteria 
- [x] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by JenMadiedo** [comment]
Closing this story will be blocked until [#157 ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/157) merges as it will require a change with the location source .csproj file for packaging

**Comment by juzuluag** [comment]
For signing the packages, there is no code signing certificate to be included at the moment.
