### ISSUE TITLE
ElectricityMapsDataSource Implementation: Forecasted Emissions

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#167]
# Description
As a Carbon Aware Application Developer, I want to get the optimal Forecasted average carbon intensity rate from the current 24-hour forecast using Electricity Maps data, so that I can schedule my Azure Batch job to run at an optimal, or green, time period and/or location.

[emissions/forecast/current API documentation](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#get-emissionsforecastscurrent)
 
# Acceptance Criteria

- [ ] Verify that if the optimal forecast for a single location is requested, then the results return Electricity Maps optimal forecast rate and time for that location
- [ ]  Verify that if the optimal forecast for multiple locations is requested, then the results return Electricity Maps optimal forecast rate and time for each location
- [ ] Verify that if the optimal forecast within a start and end time is requested for a single location, then the results return Electricity Maps optimal forecast rate and time for that location where the optimal time is within the start and end times.
- [ ] Verify that if the optimal forecast within a start and end time is requested for multiple locations, then the results return Electricity Maps optimal forecast rate and time for each location where the optimal time is within the start and end times.
- [ ] Ensure that if the forecast request contains the compute duration, then optimal average carbon intensity rate is calculated for the duration requested  
- [ ] Ensure that if the forecast request does not contain the compute duration, then optimal average carbon intensity rate is calculated from a single forecast data point
- [ ] Ensure that any errors returned from Electricity Maps is forwarded to the consumer layer
- [ ] Ensure that an error message is returned that informs the the user they are attempting to access functionality that will not work with a Free Trial subscription
- [ ] Unit Tests are completed and code passes tests
- [ ] Ensure that Forecasted Emissions Integration Tests includes Electricity Maps data source
- [ ] Ensure Electricity Map data source documentation is added.
- [ ] Ensure Documentation is added that details what forecast functionality works with a free trial and what needs a paid subscription 

# Dependencies
#179 

## GSF Backlog Reference
[[Feature Contribution]: electricityMap Plugin](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/71)

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by esgraham** [comment]
Merged
