### ISSUE TITLE
Clear access boundaries throughout SDK

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#173]
# Description
As a Carbon Aware application developer, I need to have clear access boundaries throughout the SDK, so that I am required to learn and implement the exposed classes.

[SDK as a C# Client Library](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0009-sdk-as-a-c%23-client-library.md)

# Acceptance Criteria

- [ ] Ensure that only the public classes are available to the user within the SDK

**Verify that the following WebAPI routes can be executed and return the expected results:**

 - [ ] [GET emissions/bylocation](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#get-emissionsbylocation)
 - [ ]  [GET emissions/bylocations](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#get-emissionsbylocations)
  - [ ] [GET emissions/bylocations/best](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#get-emissionsbylocationsbest)
 - [ ]  [GET emissions/forecasts/current](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#get-emissionsforecastscurrent)
  - [ ] [POST emissions/forecasts/batch](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#post-emissionsforecastsbatch)
 - [ ]  [GET emissions/average-carbon-intensity](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#get-emissionsaverage-carbon-intensity)
  - [ ] [POST emissions/average-carbon-intensity/batch](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#post-emissionsaverage-carbon-intensitybatch)

**Verify that the that following CLI routes can be executed and return the expected results:**

 - [ ] [emissions](https://github.com/microsoft/carbon-aware-sdk/blob/dev/docs/carbon-aware-cli.md#emissions)
  - [ ] [emissions-forecasts](https://github.com/microsoft/carbon-aware-sdk/blob/dev/docs/carbon-aware-cli.md#command-emissions-forecasts)

- [ ] Unit Tests are completed and code passes tests

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by gfmatthews** [comment]
At the moment, there's a wide range of places where we indicate that objects are `public` when in fact they should be `internal` or `private` or whatever is appropriate. This story is a cleanup task as noted in our SDK library design document as linked in the issue. Recommending this for approval

**Comment by juzuluag** [comment]
PR: Green-Software-Foundation/carbon-aware-sdk#256
