### ISSUE TITLE
ElectricityMapsDataSource Implementation: Measure Emissions

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#174]
# Description
As a Carbon Aware Application Developer, I want to get the actual average carbon intensity rate using Electricity Maps data, so that I can that I can get the Average Marginal Carbon Intensity rate for an Azure Batch job.

[emissions/average-carbon-intensity API documentation](https://github.com/microsoft/carbon-aware-sdk/tree/dev/src/CarbonAware.WebApi/src#get-emissionsaverage-carbon-intensity)

 
# Acceptance Criteria

- [ ] Ensure that if the configuration is set to use Electricity Maps for emissions, then the results return Electricity Maps' average carbon intensity rate for that location and time period
- [ ] Ensure that an error is returned that lets the user know their subscription does not have access to the past range route if the subscription does not have access and the time period is greater than 24 hours in the past and to contact Electricity Maps for more information.
- [ ] Ensure that an error is returned that lets the user know their subscription does not have access to the route or zone and to contact Electricity Maps for more information.
- [ ] Ensure that if the custom config are values of emissionFactorType and disableEstimations are set, then the values are sent to Electricity Map for emissionFactorType or disableEstimations
- [ ] Ensure that if the custom config value are not set, then no values are sent to Electricity Map for emissionFactorType or disableEstimations
- [ ] If a custom config value for emissionFactorType is not 'direct' or 'lifecycle' the value is sent to Electricity Maps, and the error is handled by Electricity Maps and forwarded to the consumer layer.
- [ ]  Ensure that an error message is returned that informs the the user they are attempting to access functionality that will not work with a Free Trial subscription
- [ ] Unit Tests are completed and code passes tests
- [ ] Ensure documentation is updated with Electricity Maps limitations and custom parameters.
- [ ]  Ensure Documentation is added that details what forecast functionality works with a free trial and what needs a paid subscription

# Dependencies

#167 

## GSF Backlog Reference
[[Feature Contribution]: electricityMap Plugin](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/71)

# Task List
- [ ] List of tasks (punch list) needed to complete the user story

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [x] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [x] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by gfmatthews** [comment]
Approving. Note that this only covers backwards looking data. A separate story exists for other routes that will need to support Electricity Map data.

**Comment by pritipath** [comment]
Merged in GSF
