### ISSUE TITLE
Create a branch strategy to facilitate feedback on the API design

### ISSUE THREAD

**Issue by gfmatthews** [microsoft/carbon-aware-sdk#176]
# Description
As a consumer of the API, I want to have a single branch to point to so that I can give feedback on the API design

# Acceptance Criteria

- [x] A branch _`release`_ exists with the API library changes and any other relevant PRs / commits needed to facilitate real-world usage of the C# library (using just WattTime data is okay)
- [x] Instructions and clear delineation are available so that engineers know when PRs have to be made to both  _`release`_ and to the GSF parent repo

# Dependencies

# Task List
- [x] Create  _`release`_
- [x] Merge appropriate PRs / commits into  _`release`_
- [x] Create / circulate understanding of what criteria necessitate merging into both  _`release`_ and to the GSF repo

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [x] External / 3rd Party dependencies identified
- [x] Engineering team understands acceptance criteria 
- [x] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by bderusha** [comment]
The appropriate commit history now exists on the branch [rc-milestone1](https://github.com/microsoft/carbon-aware-sdk/tree/rc-milestone1)

final names and process still pending

**Comment by esgraham** [comment]
Complete
