### ISSUE TITLE
Sample Azure Function App with C# Library

### ISSUE THREAD

**Issue by gfmatthews** [microsoft/carbon-aware-sdk#177]
# Description
As a SDK consumer, I want to look at an example Azure Function  app so I can see how the API would get called in a real-world scenario and learn how to structure my own usage of the API.

# Acceptance Criteria

- [ ] Azure Function app that can be loaded and debugged on any machine with dotnet core.
- [ ] No dependencies on Azure or other external services apart from the C# CA-SDK library
- [ ] Demonstrated minimum viable usage of the API
- [ ] Tests demonstrate usage of json data sources as mocks for the real data sources
- [ ] Code demonstrated how to configure credentials for WattTime / ElectricityMap and how to configure the aggregator to point to whichever data source.

# Dependencies

- #160 

# Task List
- [ ] Split az func to be for IEmissions and IForecast
- [ ] Integrate into pipeline to build automatically
- [ ] Integrate into pipeline to run
- [ ] Perform emissions requests against az func running.
- [ ] Document any extra vscode packages needed to be able to run func.
- [ ] Review docs to ensure clear about what is local, and what requires azure deployment as an example.

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by esgraham** [comment]
There is a sample Console App in the Branch for #171 .  I was able to use the code in the Console sample to get an Azure Function up and running.  Please review and evaluate if we need more in the console app.

**Comment by gfmatthews** [comment]
Love the sample that was checked in as part of that commit and I think that's a great place to start. It has the conceptual level of complexity that I think we need here. That said, I think we can revisit this once we have the full library built out to have a full living artifact that is a good representation of the library at that time.

**Comment by JenMadiedo** [comment]
PR merged
