### ISSUE TITLE
Create ElectricityMap Client

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#178]
# Description
In order to have access to Electricity Map content, there is a need to implement a `C#` client that can fetch data from `https://api.electricitymap.org` endpoints.
Stories [167](https://github.com/microsoft/carbon-aware-sdk/issues/167) and [174](https://github.com/microsoft/carbon-aware-sdk/issues/174) can use this new data source client so these can be implemented.

 
# Acceptance Criteria

- [ ] Connect to `https://api.electricitymap.org` endpoints to fetch forecast and emissions data
- [ ] Be able to pass user's token to EM client.

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story
- [ ] Implement HTTP client that can handle HTTP requests for `forecast` and `average carbon intensity` routes (`../carbon-intensity/forecast` , `../carbon-intensity/past-range`).
- [ ] Enhance HTTP Client Configuration, so credentials can be passed on.
- [ ] Handle gracefully EM exceptions.
- [ ] Enhance Location lookup for HTTP Client.
- [ ] Add unit tests.
- [ ] Add support to handle HTTP proxy configuration.
- [ ] Add documentation.

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?
