### ISSUE TITLE
Implement Electricity Maps HTTP Client

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#179]
# Description
As a Carbon Aware SDK Developer, I want to login and connect to Electricity Maps API service, so that I can use Electricity Map as a data source.

<Link to Design if available>

# Acceptance Criteria
- [x] Verify that the client can pass credentials to Electricity Map API
- [x] Ensure that the Electricity Maps client can connect to https://api.electricitymap.org endpoints.
- [ ] Ensure that the Electricity Maps API can be called through a proxy [similar to WattTime data source]
- [x] Ensure that any errors returned from Electricity Maps is forwarded to the consumer layer
- [ ] Unit Tests are completed and code passes tests
- [ ] Ensure Electricity Map client documentation is added.
- [ ] A strategy exists for how and when to update the mappings between API endpoints should Electricity Map update their API at some point in the future (i.e. versioning support)

# Dependencies

GSF Backlog Reference
https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/71

# Task List
- [x] Implement HTTP client that can handle HTTP requests
- [x] Enhance HTTP Client Configuration, so credentials can be passed on.
- [x] Implement Error Handling
- [x] Implement lookup for Routes supported for HTTP Client.
- [x] Implement Proxy Service
- [ ] Add unit tests.
- [ ] Add documentation.

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [x] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by gfmatthews** [comment]
Approving. Please take a look at the full acceptance criteria list since I added a note in there about versioning.

**Comment by esgraham** [comment]
Work will continue in  #167
