### ISSUE TITLE
Add Forecast by Date to C# Library Contract

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#192]
# Description
As a developer of a carbon-aware application, I want to consume the Forecast by Date as a C# library so that I can run the SDK within a single application.

Note:  Past Forecasts are not available in Electricity Maps.  Testing will need to occur with WattTime.

# Acceptance Criteria

- [x] Ensure the developer can access the getCarbonIntensityForecastAsync Data Source function
- [x] Ensure that the forecast response is returned to the application when the function is called with past dates
- [x] Unit Tests are completed and the code passes tests
- [x] Documentation and examples are provided for C# Library Forecast

# Dependencies

#160 
#166 

# Task List
- [X] Add `GetForecastByDateAsync()` to IForecastHandler
- [X] Implement `GetForecastByDateAsync()` in ForecastHandler
- [X] Add unit tests
- [X] Add documentation updates

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [x] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [x] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by esgraham** [comment]
Updating to remove batch, but add past forecast capabilities

**Comment by JenMadiedo** [comment]
merged
