### ISSUE TITLE
Add Emissions Location and Best Contract to the C# Library

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#193]
# Description
As a developer of a carbon-aware application, I want to consume the Emissions Location and Best routes as a C# library so that I can run the SDK within a single application.

<Link to Design if available>

# Acceptance Criteria

- [x] Ensure the developer can access the emissions/bylocation function
- [x] Ensure that the carbon intensity result for a single location is returned to the application when the bylocation function is called
- [x] Ensure the developer can access the emissions/bylocations function
- [x] Ensure that the carbon intensity results for multiple locations are returned to the application when the bylocations function is called
- [x] Ensure the developer can access the emissions/bylocations/best function
- [x] Ensure that the lowest carbon intensity result for multiple locations is returned to the application when the bylocations/best function is called
- [x] Unit Tests are completed and code passes tests
- [x] Documentation and examples are provided for C# Library Emissions

# Dependencies

#160 
#166 

# Task List
- [x] Add GetEmissionsDataAsync path
- [x] Add GetBestEmissionsDataAsync path
- [x] Add GetAverageCarbonIntensityBatchAsync path
- [x] Add Unit Tests
- [x] Add Library documentation

# Sprint-Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Acceptance criteria is verifiable / testable 
- [x] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [x] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by esgraham** [comment]
Meged
