### ISSUE TITLE
Migrate Carbon Aware WebApi to consume CA library

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#209]
# Description
As a Carbon Aware Developer, I want to have the CA WebAPI consumer layer use the Carbon Aware Library so that changes can be made in a single place: the CA Library.

# Acceptance Criteria

- [ ] Ensure that the WebAPI consumer layer routes all requests through the Carbon Aware Library.
- [ ] Unit Tests are completed, and the code passes tests
- [ ] Update Documentation, including Architecture diagrams, if needed

# Dependencies

# Task List
- [ ] List of punch list) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable/testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by gfmatthews** [comment]
Approving - this is a good first issue for some of the new engineers on the team

**Comment by Kpopovs1** [comment]
PR opened: Green-Software-Foundation#245
