### ISSUE TITLE
Improve location files handler when dealing with duplicated keys.

### ISSUE THREAD

**Issue by gfmatthews** [microsoft/carbon-aware-sdk#214]
# Description
As a Carbon Aware application developer, I want that location source keys don't collide

# Acceptance Criteria

 - [X] Avoid missing location definitions to be missed as part of loading the application
 - [X] Avoid location key collisions when loading location definitions from different locations-source json files
 - [X] Unit Tests are completed and code passes tests

# Dependencies

# Task List
 - [X] Load all the locations definitions from all the json files
 - [X] Generate new key if there is key name collision.
 - [X] Add unit test to verify key name renaming.

**Comment by gfmatthews** [comment]
@juzuluag - Can you provide a bit more detail in this issue on what your plan is? We talked about it planning but it's good to keep it here for the record

**Comment by juzuluag** [comment]
@gfmatthews , this is what this is about:
- **Background**: Current Location files handler (`CarbonAware.LocationSources` project) discovers all the location json files located at `location-sources\json` that contains `NamedGeoposition` instances. 
- **Issue**: `NamedGeoposition` instances are stored in a dictionary. If there are multiple instances that generates the same key, it will override the previous ones stored (a.k.a: name collision). Creating missing instances and potentially confusing the user that relies on some of those instances. Currently there isn't any feedback (i.e. log warning) to the user.
- **Proposal**: The location handler should warn the user of name collision. If there is collision , we could generate new keys. This is not the ideal, since what is missing, is another feature/story , that listing locations should be available to the end user (expose this new functionality using the API)

**Comment by juzuluag** [comment]
PR: Green-Software-Foundation#239
