### ISSUE TITLE
Keep packages/lib versions consistent across projects

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#218]
# Description
All projects need to be reviewed to ensure that projects are using the same version of packages or libraries.

# Acceptance Criteria

- [ ] Ensure the review process is automated
- [ ] Ensure the pipeline checks to verify that all projects are then updated when a package is updated.
- [ ] Unit Tests are completed and code passes tests

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?
