### ISSUE TITLE
Allow nullable for CarbonAware.csproj

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#219]
# Description
CarbonAware.csproj is the original project and it does not have the flag set to allow nullable objects. 

# Acceptance Criteria

- [x] Ensure that the EnableNullableOjects flag is set in the CarbonAware.csproj
- [x] Ensure that all warnings that an object is not typed are fixed by adding a type
- [x] Unit Tests are completed and code passes tests

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by JenMadiedo** [comment]
PR: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/237

**Comment by JenMadiedo** [comment]
PR merged
