### ISSUE TITLE
Move WattTimeClient into WattTime project directory

### ISSUE THREAD

**Issue by esgraham** [microsoft/carbon-aware-sdk#220]
# Description
WattTime Client was created as a separate project from the WattTime DataSource project. As we have moved forward with the SDK, the WattTime data source is tightly integrated into the Client. 

# Acceptance Criteria

- [x] Ensure the WattTime Client project is located in the WattTime directory.
- [x] Ensure all references to the WattTime Client project are updated
- [x] Unit Tests are completed and code passes tests

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by JenMadiedo** [comment]
PR merged
