### ISSUE TITLE
ADR-0004: Move/update GettingStarted.md content

### ISSUE THREAD

**Issue by bderusha** [microsoft/carbon-aware-sdk#223]
## User Story
As a carbon aware sdk user, I want all relevant docs to exist in the `/docs` directory, per the standard set by ADR-0004, so I can have consistent expectations about where to go for content.

### Design Goals
- Find a home for all existing `GettingStarted.md` content.
- Understand the difference between `GettingStarted` and `quickstart` and make it clearer (or merge if no difference).
- Markdown-lint compliant

# Task List
- [ ] Moving `GettingStarted.md` (GS) into docs
- [ ] Review GS and `quickstart.md` (QS) and identify similarities/overlap in content
- [ ] Decide whether GS ans QS should be merged into a single doc or own different spheres (idea: one is architecture focused; one code focused....)
- [ ] Leverage outcome ^^ to also help guide new users on navigating other documentation

## Acceptance Criteria

- [ ] `GettingStarted.md` no longer exists in the root directory
- [ ] User have a clear guide for starting out with the SDK
- [ ] All unique pieces of information from the original `GettingStarted.md` can be found somewhere in `/docs`
- [ ] Content touched is markdown-lint compliant

**Comment by JenMadiedo** [comment]
@Kpopovs1 taking point, with @JenMadiedo. Will circle back with @in4margaret when she returns.
