### ISSUE TITLE
Documenting Dynamic Data Source Registration

### ISSUE THREAD

**Issue by gfmatthews** [microsoft/carbon-aware-sdk#228]
# Description
As a Carbon Aware application developer, I would like to decouple the data sources from the SDK into their own nuget packages and create a mechanism to allow auto discovery and dynamic registration. This will allow for new data sources to be plugged in with minimum configuration and dependency on the existing code base.

# Acceptance Criteria

Create a document that defines -

- [x] High level approach
- [x] Benefits of doing this
- [x] Level of effort required and the risks
    

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by juzuluag** [comment]
PR: Green-Software-Foundation/carbon-aware-sdk#288
