### ISSUE TITLE
Add Location lookup to API SDK, WebApi, CLI.

### ISSUE THREAD

**Issue by gfmatthews** [microsoft/carbon-aware-sdk#229]
Adding reference to an existing GSF issue Green-Software-Foundation/carbon-aware-sdk#175

# Description
As a Carbon Aware application developer, I want to list all the locations definitions as part of an WebApi endpoint, cli command and GSF.CarbonAware handler.

# Acceptance Criteria

 - [X] List all the location instances loaded from the json files definitions
 - [X] Be able to use WebApi, CLI and SDK to list all locations entries.
 - [X] Unit Tests are completed and code passes tests

# Dependencies

# Task List
 - [X] Enhance WebApi to add new route `/locations`
 - [X] Enhance CLI commands with new command `locations`
 - [X] Enhance GSF.CarbonAware SDK to include new Locations handler.
 - [X] Add Unit tests
 - [X] Add Integrations tests
 - [X] Update documentation

**Comment by juzuluag** [comment]
Adding reference to #214

**Comment by juzuluag** [comment]
PR: Green-Software-Foundation#239
