### ISSUE TITLE
Update EM and WattTime Client Tests to use a real moq for httpClient message handling

### ISSUE THREAD

**Issue by JenMadiedo** [microsoft/carbon-aware-sdk#237]
# Description
As a Carbon Aware application developer, I want a standard moq infrastructure for writing client tests.

See: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/194#discussion_r1029824842

# Acceptance Criteria

 - [X] Remove custom mocks of http class in client tests
 - [X] Client tests use Moq.Protected and have clear path for replicating/adding more tests
 - [X] Unit Tests are completed and code passes tests

# Dependencies

# Task List
 - [X] Remove custom mock of http class in `ElectricityMapsClientTest`
 - [X] Remove custom mock of http class in `WattTimeClientTest`
 - [X] Use Moq.Protected to simulate Http Client

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by JenMadiedo** [comment]
PR: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/240
