### ISSUE TITLE
Improve unit test coverage + style

### ISSUE THREAD

**Issue by JenMadiedo** [microsoft/carbon-aware-sdk#240]
# Description
As a Carbon Aware application developer, I want to know that all the existing codepaths have been unit tested to ensure bugs are caught

# Acceptance Criteria

- [x] Ensure that all external client functions (WebAPi, CLI, and Library) are fully unit tested and code coverage confirms (ignoring non-testable code paths). Example of `forecast/batch` not having tests.
- [x] Ensure that the main aggregator and data source functions (which are part of a flow from the client) are fully unit tested and code coverage confirms (ignoring non-testable code paths)
- [x] Condense redundantly similar tests into single test with multiple test cases (exception throwing, null/edge cases are good ones usually)
- [x] Ensure complex functions have edge case testing too, not just happy path

# Dependencies

# Task List
- [x] Review WebApi tests
- [x] Review CLI tests
- [x] Review CA Library tests
- [x] Review Data Sources tests
- [ ] Open draft PR

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by juzuluag** [comment]
PR #298
