### ISSUE TITLE
Improve integration test coverage

### ISSUE THREAD

**Issue by JenMadiedo** [microsoft/carbon-aware-sdk#241]
# Description
As a Carbon Aware application developer, I want to know that all the existing codepaths have had robust integration tests to ensure no flows are broken end-to-end when new features are added

# Acceptance Criteria

- [ ] Ensure that all external client functions (WebAPi, CLI, and Library) are fully integration tested and code coverage confirms (ignoring non-testable code paths). Example of `forecast/batch` not having tests.
- [ ] Ensure that integration tests are consistent across the client functions aka same things are tested for all external functions

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?
