### ISSUE TITLE
Improve experience for free trial users of Electricity Maps

### ISSUE THREAD

**Issue by JenMadiedo** [microsoft/carbon-aware-sdk#242]
# Description
As a Carbon Aware application developer using the free trial of electricity maps, I want to know what the limitations of the SDK are for me and have as close an experience to a full token user as possible.

# Acceptance Criteria

- [x] Ensure that all the special note about have a free trial token (different header, different token, routes available, connection limits etc.) are documented
- [x] Ensure that in places when more information can be provided to free trial users (a failure that is unique to those users and not token users), we check and provide the appropriate response.

# Dependencies

# Task List
- [X] Update documentation on limitation
- [X] Add validation for mismatched configuration (token url needs 'auth-token' header versus trial url needs 'X-BLOBR-KEY' header)
- [X] Add unit tests for validation
- [X] Add better error messaging at failure point for free trial users

# Sprint-Ready Checklist 
- [X] Acceptance criteria defined 
- [X] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by juzuluag** [comment]
PR https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/267
