### ISSUE TITLE
Migrate Handlers in CA library to directly consume the data sources (remove dependency on Aggregators)

### ISSUE THREAD

**Issue by gfmatthews** [microsoft/carbon-aware-sdk#243]
# Description
As a Carbon Aware Developer, I want the datasource handlers (EmissionHander, ForecastHandler) to directly call the datasource and remove the overhead of having Aggregators in between so that the code is cleaner and extensible. 
This would prevent from creating a new Aggregator layer every time a new data source interface is created. 

# Acceptance Criteria

- [x] Ensure that the CA library consumes the Datasources directly.
- [x] Remove reference to the Aggregator project 
- [x] Mark Aggregator methods with 'deprecated' flag
- [x] Unit Tests are completed, and the code passes tests
- [x] Update Documentation, including Architecture diagrams, if needed

# Dependencies

# Task List
- [ ] List of tasks (punch list) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria are verifiable/testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by juzuluag** [comment]
PR: Green-Software-Foundation/carbon-aware-sdk#253
