### ISSUE TITLE
Add PS scripts for create/add GSF package

### ISSUE THREAD

**Issue by JenMadiedo** [microsoft/carbon-aware-sdk#244]
Currently there are only `bash` scripts available under `scripts/package` and it limits the scope of integration for a Windows user.

# Description
As a Carbon Aware application developer using Windows, I would like `powershell` script equivalents of the `bash` scripts available under `scripts/package` so I can run these scripts directly in my environment.

# Acceptance Criteria

- [ ] Create `add-packages.ps` and `create-packages.ps` powershell scripts
- [ ] Ensure that scripts run as intended on windows machines.

# Dependencies

# Task List
- [ ] Write powershell scripts
- [ ] Make sure they pass

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?
