### ISSUE TITLE
Azure API Management Sample

### ISSUE THREAD

**Issue by JenMadiedo** [microsoft/carbon-aware-sdk#246]
## User Story
As an Azure APIM user, I want to be able to connect to the carbon aware SDK from my policy to make my implementation carbon aware.

### Design Goals
- Provide an example of how users can integrate the carbon aware SDK into APIM
- Provide an example policy that uses the carbon aware SDK to make decisions about routing.

# Task List
- [ ] Add policy samples
- [ ] Add readme docs

## Acceptance Criteria

- [ ] `GettingStarted.md` no longer exists in the root directory
- [ ] User have a clear guide for starting out with the SDK
- [ ] All unique pieces of information from the original `GettingStarted.md` can be found somewhere in `/docs`
- [ ] Content touched is markdown-lint compliant

**Comment by juzuluag** [comment]
PR: Green-Software-Foundation/carbon-aware-sdk#257
