### ISSUE TITLE
The Aggregators are dead, long live the Handlers

### ISSUE THREAD

**Issue by pritipath** [microsoft/carbon-aware-sdk#247]
# Description
In order to improve the maintainability and readability of the codebase, I want to delete the Aggregators project and any references to it from the Consumers (WebAPI and CLI). The pre work for this is done as part of #243 where the business logic present in the Aggregators was migrated to Handlers. 

# Acceptance Criteria

- [x] No references to Aggregators exist from WebApi & CLI.
- [x] Aggregator project is deleted  
- [x] Unit Tests are completed, and the code passes tests
- [x] Documentation is updated, including Architecture diagrams, if needed

# Dependencies

# Task List
- [ ] List of tasks (punch list) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria are verifiable/testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by juzuluag** [comment]
PR Green-Software-Foundation/carbon-aware-sdk#276
