### ISSUE TITLE
[Bug] WattTime password enconding non-ASCII

### ISSUE THREAD

**Issue by JenMadiedo** [microsoft/carbon-aware-sdk#249]
# Description
As a Carbon Aware application developer, I need to be able to encode by WattTime password even with non-ASCII characters

# Acceptance Criteria

- [ ] Move to UTF-8 encoding instead of ASCII for credentials

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by JenMadiedo** [comment]
See GSF bug: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/181
