### ISSUE TITLE
Move CarbonAwareParameters class to CarbonAware package

### ISSUE THREAD

**Issue by JenMadiedo** [microsoft/carbon-aware-sdk#251]
# Description
As a developer in the CarbonAware SDK, I want the CarbonAwareParameters class that is shared by all clients of the SDK to live in the main Carbon Aware project

# Acceptance Criteria

- [ ] Move CarbonAwareParameters in to the CarbonAware project
- [ ] Ensure tests pass

# Dependencies

# Task List
- [ ] Move carbon aware parameters class to carbon aware project
- [ ] Update references in Library, WebAPI and CLI
- [ ] Update unit tests

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by juzuluag** [comment]
PR: Green-Software-Foundation/carbon-aware-sdk#285
