### ISSUE TITLE
Free Version of Electricity Maps (CO2Signal)

### ISSUE THREAD

**Issue by shineyk** [microsoft/carbon-aware-sdk#252]
# Description
Treat [Electricity Maps](https://www.electricitymaps.com/) ("Electricity Maps Paid") and [CO2Signal](https://www.co2signal.com/) ("Electricity Maps Free") as different, unrelated data sources. Since the CO2Signal API and Electricity Maps API diverge its worth making a new endpoint that supports CO2Signal.

Refer to GSF issue for more details and comment thread: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/261

# Acceptance Criteria

- [x] New datasource/endpoint for CO2Signal ("Electricity Maps Free")
- [x] Architecture matches GSF Architecture
- [x] Unit tests are passing
- [x] Integration tests are passing

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by FabioTurati-NTT** [comment]
Hello, just wanted to let you know that I've reopened my PR (https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/261). I closed it by mistake, it was not intentional.

**Comment by FabioTurati-NTT** [comment]
Come to think about it: @shineyk, are you interested in this feature? Would you like to contribute to it? I could use some help with the unit tests, and in general to improve my code!

**Comment by FabioTurati-NTT** [comment]
@JenMadiedo I would like to coordinate with you and your team, to make sure that we are not both working on the same thing. I already have a first implementation of EM Free, if you want to have a look you can find the details at https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/261#issuecomment-1426229964

But maybe your focus is on the free trial of the paid version, which is a different thing.

It would be great if one of you could join tomorrow's Carbon Aware SDK sync meeting!

**Comment by shineyk** [comment]
Hi @FabioTurati-NTT  - thanks for reaching out, we're going to discuss today and get back to you.

**Comment by shineyk** [comment]
Hi @FabioTurati-NTT , @JenMadiedo and @pritipath will join tomorrow's sync meeting to discuss collaboration on this. Thanks!

**Comment by JenMadiedo** [comment]
Outcome from the sync this morning with @pritipath, @FabioTurati-NTT and others, we decided that Fabio will continue the implementation on his branch, as this is a great learning opportunity and way to get more external contributors into the Carbon Aware SDK. I will be available if he has any questions, and he will tag us in the PR once it's ready for review.
