### ISSUE TITLE
Configuration for selecting WattTime model version

### ISSUE THREAD

**Issue by shineyk** [microsoft/carbon-aware-sdk#253]
# Description

- What are the implications of supporting different WattTime model versions?
- What's needed to support the different methods (WebAPI, CLI, library)?
- How would/could the user select a version (UX/UI)?
- How would we handle a difference of data schema between versions? (Example: new/removed/modified columns)

GSF Issue for reference: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/260

# Acceptance Criteria

- [ ] Documentation the findings to the questions / unknowns
- [ ] Documenting additional questions that come up
- [ ] An ADR to share with GSF
- [ ] A list of stories to add to backlog

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by JenMadiedo** [comment]
After discussion with the team, we decided this would be best handled by someone in GSF as the process for doing this (if that's the route they choose) would likely require a long-term relationship with WattTime. Made that note in the [GSF ticket](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/260#issuecomment-1433653760) and closing this issue on our end.
