### ISSUE TITLE
Design for a CSV output option for CLI

### ISSUE THREAD

**Issue by shineyk** [microsoft/carbon-aware-sdk#255]
# Description
Currently the CLI output is in JSON format. We want to create an option to output in CSV. 
* Is JSON treated as a default? What should the new default be?
* Should the default be configurable?
* What should the command line option be called?
* Should this option be optional?

GSF issue: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/35

# Acceptance Criteria

- [ ] Answers/findings to the questions added as an ADR, including any other design considerations
- [ ] Additional stories added to the backlog for implementation 

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?
