### ISSUE TITLE
[Bug]: WebAPI and CLI returns results specific to each time zone where it deployed. Need to change to UTC.

### ISSUE THREAD

**Issue by in4margaret** [microsoft/carbon-aware-sdk#257]
# Description

As a developer  I want to see predicted results for CA Web API responses regardless where it is deployed. 

# Acceptance Criteria

- [ ] Web API returns result in UTC
- [ ] Passing integration tests in Web API

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?

**Comment by juzuluag** [comment]
PR Green-Software-Foundation/carbon-aware-sdk#299
