### ISSUE TITLE
Improve Json Data Source data

### ISSUE THREAD

**Issue by JenMadiedo** [microsoft/carbon-aware-sdk#258]
As a Carbon Aware SDK user, I want to be able to use the JSON data source to query for emissions and forecast data. I want to be certain that the data source is working as expected E2E.

# Description

- Add Forecast data to Json data source to enable forecast endpoints
- Enable Integration tests/unit tests for forecast paths of the data source
- Fix Json integration tests using static file (previous there was a but where integration tests broke because the dates in the static Json file became the past. Currently tests on the fly add an entry to the file so it won't break but we should re-think how we auto-generate)

# Acceptance Criteria

- [ ]  JsonDataSource.cs implements IForecastDataSource. 
- [ ] AzureRegionTestDataGenerator.cs generates data compatible with IForecastDataSource  implementation for JsonDataSource
- [ ] Json Data Source Mocks generates data needed for Forecast Integration tests.
- [ ] Forecast Endpoints are enabled for Json
- [ ] JSON unit tests pass
- [ ] Integration tests with Json pass for Emissions & Forecast endpoints
- [ ] Documentation is updated describing new forecast features given Json data source

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?
