### ISSUE TITLE
Configure data sources directly from CLI

### ISSUE THREAD

**Issue by JenMadiedo** [microsoft/carbon-aware-sdk#259]
As a Carbon Aware SDK CLI user, I would like to configure the data source directly from the CLI interface.

# Description

- Add new `caw configure` command that allow users to manually edit the config file.
- Decide if any flaggs/affordances will be added on the command
- Add unit tests
- Add relevant documentation

# Acceptance Criteria

- [ ] New CLI command `configure`
- [ ] Ensure unit tests pass
- [ ] Ensure integration tests pass
- [ ] Ensure docs are updated

# Dependencies

# Task List
- [ ] List of tasks (punchlist) needed to complete the user story

# Sprint-Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified
- [ ] Engineering team understands acceptance criteria 
- [ ] Is the user story small enough to be implemented in a short amount of time, but large enough to provide value?
